import { Pandal } from './types';

export const KOLKATA_CENTER: [number, number] = [22.5726, 88.3639];
export const DEFAULT_ZOOM = 13;

export const pandals: Pandal[] = [
  // ── Central Kolkata & Park Grounds ─────────────────────────────────────────
  {
    id: 'santosh-mitra-square',
    name: 'Santosh Mitra Square (Lebutala Park)',
    nameBengali: 'সন্তোষ মিত্র স্কোয়ার (লেবুবাগান পার্ক)',
    lat: 22.5660201,
    lng: 88.3656532,
    zone: 'central',
    theme: 'Swarna Mandir & Laser Extravaganza',
    themeDescription:
      "Central Kolkata's premier pandal held right inside Santosh Mitra Square Park (Lebutala Park), off BB Ganguly Street & Nirmal Chandra Street. Renowned across Bengal for monumental architectural marvels and synchronized 3D laser shows.",
    theme2026:  'Digital Jyoti & Architectural Wonder',
    themeDescription2026:  'Central Kolkata\'s premier digital light and projection mapping marvel inside Lebutala Park, combining monumental temple architecture with synchronized light art.',
    mustWatch: [
      'Built entirely inside Santosh Mitra Square Park ground',
      'Pioneers of synchronized 3D laser & light show in Kolkata',
      'Direct walking route from Sealdah Station and Central Metro',
      'Kolkata Police designated dedicated queue corridor',
    ],
    artist: 'Pradip Ghosh',
    organizer: 'Santosh Mitra Square Puja Committee',
    established: 1936,
    timings: '24 hours (Saptami to Dashami)',
    bestTime: '8 PM – 1 AM',
    entryFee: 'Free',
    tags: ['park', 'monumental', 'laser-show', 'central', 'police-guide'],
    rating: 4.9,
    imageEmoji: '✨',
  },
  {
    id: 'college-square',
    name: 'College Square',
    nameBengali: 'কলেজ স্কোয়ার',
    lat: 22.5745279,
    lng: 88.3644724,
    zone: 'central',
    theme: 'Swarna Bhaban & Sarobar Illumination',
    themeDescription:
      "Held in the heart of Kolkata's academic district around College Square lake on Bankim Chatterjee Street. Celebrated worldwide for its dazzling lighting display reflecting across the central water tank.",
    theme2026:  'Sarobar Bhaban & Water Reflection',
    themeDescription2026:  'A dazzling Chandannagar illumination spectacle reflected across the central College Square lake, recreating grand historic Indian water palace architecture.',
    mustWatch: [
      'Reflection of the illuminated structure across College Square lake',
      'Traditional Chandannagar illumination masterwork',
      'Heart of Kolkata book market and Indian Coffee House',
      'Kolkata Police managed entry from Surya Sen Street',
    ],
    artist: 'Rintu Das',
    organizer: 'College Square Puja Committee',
    established: 1942,
    timings: '10 AM – 2 AM',
    bestTime: '8 PM – 12 AM',
    entryFee: 'Free',
    tags: ['heritage', 'lake', 'illumination', 'central', 'police-guide'],
    rating: 4.8,
    imageEmoji: '🏛️',
  },
  {
    id: 'mohammad-ali-park',
    name: 'Mohammad Ali Park',
    nameBengali: 'মহম্মদ আলি পার্ক',
    lat: 22.5771888,
    lng: 88.36073689999999,
    zone: 'central',
    theme: 'Mahabharat – The Epic Heritage',
    themeDescription:
      "Set inside the famous Mohammad Ali Park on Chittaranjan Avenue (MG Road crossing). Famous for monumental temple replicas and traditional idol craftsmanship right opposite Calcutta University.",
    theme2026:  'Ancient Temple Architecture of India',
    themeDescription2026:  'Recreating the timeless beauty of ancient Indian stone temple architecture with detailed carvings, classical pillars, and heritage sanctum aesthetics.',
    mustWatch: [
      'Located inside Mohammad Ali Park ground off CR Avenue',
      'Magnificent architectural palace replica',
      'Close to MG Road Metro Station (Line 1)',
      'Nightly aarti with Vedic chants and live classical music',
    ],
    artist: 'Pradip Das',
    organizer: 'Mohammad Ali Park Puja Committee',
    established: 1930,
    timings: '10 AM – 2 AM',
    bestTime: '6 PM – 11 PM',
    entryFee: 'Free',
    tags: ['mythology', 'park', 'grand', 'central', 'police-guide'],
    rating: 4.8,
    imageEmoji: '⚔️',
  },
  {
    id: 'chorbagan',
    name: 'Chorbagan Sarbojanin',
    nameBengali: 'চোরবাগান সর্বজনীন',
    lat: 22.5834284,
    lng: 88.3635965,
    zone: 'central',
    theme: 'Shilpa Gram',
    themeDescription:
      "Tucked off Muktaram Babu Street near Ram Mohan Sarani in Central Kolkata. Revered for pure artistic installation and sensitive rural Bengal aesthetics.",
    theme2026:  'Beyond Sound (Shobder Opare)',
    themeDescription2026:  'An acclaimed sensory and acoustic art installation exploring the metaphysics of sound, resonance, and inner meditative silence crafted by master Bengal sculptors.',
    mustWatch: [
      'Walking distance from Mohammad Ali Park and MG Road',
      'Exquisite clay craftsmanship and terracotta relief',
      'Consistently wins prestigious aesthetic accolades',
    ],
    artist: 'Bhabatosh Sutar',
    organizer: 'Chorbagan Sarbojanin Puja Committee',
    established: 1938,
    timings: '10 AM – 2 AM',
    bestTime: '7 PM – 10 PM',
    entryFee: 'Free',
    tags: ['artistic', 'heritage', 'terracotta', 'central'],
    rating: 4.7,
    imageEmoji: '🎨',
  },
  {
    id: 'shimla-byayam',
    name: 'Shimla Byayam Samiti',
    nameBengali: 'শিমলা ব্যায়াম সমিতি',
    lat: 22.5840,
    lng: 88.3650,
    zone: 'central',
    theme: 'Lal Mati & Swadeshi Heritage',
    themeDescription:
      "Established during India's freedom struggle on Vivekananda Road. Known for patriotic history, traditional pratima, and physical culture heritage.",
    mustWatch: [
      'Pioneer of nationalist swadeshi puja since 1926',
      'Traditional Ekchala Durga pratima',
      'Immersion process with traditional akhara athletics',
    ],
    artist: 'Ramkrishna Hansda',
    organizer: 'Shimla Byayam Samiti',
    established: 1926,
    timings: '8 AM – 1 AM',
    bestTime: '7 PM – 10 PM',
    entryFee: 'Free',
    tags: ['swadeshi', 'traditional', 'freedom-struggle', 'central'],
    rating: 4.6,
    imageEmoji: '🏡',
  },
  {
    id: 'taltala-sarbojanin',
    name: 'Taltala Sarbojanin (Lord Sinha)',
    nameBengali: 'তালতলা সর্বজনীন',
    lat: 22.5535,
    lng: 88.3580,
    zone: 'central',
    theme: 'Eikya – Harmony in Heritage',
    themeDescription:
      "Core Central Kolkata puja featured on Kolkata Police Guide Zone I map near Lenin Sarani, Lord Sinha Road, and Taltala Children's Park.",
    mustWatch: [
      'Community harmony festival celebrating Central Kolkata heritage',
      'Grand illumination across Lord Sinha Road and SN Banerjee Road',
      'Convenient walk from Esplanade and Chandni Chowk Metro',
    ],
    artist: 'Ramen Sarkar',
    organizer: 'Taltala Sarbojanin Committee',
    established: 1942,
    timings: '10 AM – 2 AM',
    bestTime: '8 PM – 11 PM',
    entryFee: 'Free',
    tags: ['central', 'heritage', 'police-guide'],
    rating: 4.5,
    imageEmoji: '🕊️',
  },

  // ── North Kolkata Heritage & Parks ─────────────────────────────────────────
  {
    id: 'bagbazar',
    name: 'Bagbazar Sarbojanin',
    nameBengali: 'বাগবাজার সর্বজনীন',
    lat: 22.6044897,
    lng: 88.36561499999999,
    zone: 'north',
    theme: 'Shonar Bangla – Sabeki Ekchala',
    themeDescription:
      "A centenary celebration of Bengal's golden heritage, situated at Bagbazar Durgotsav ground near Bagbazar Ghat and Girish Avenue. Kolkata's premier traditional community puja.",
    theme2026:  'Sabeki Ekchala Durgotsav & Daaker Saaj',
    themeDescription2026:  'Kolkata\'s most revered 107-year-old traditional community puja, preserving the pure heritage of classical Ekchala Pratima with Daaker Saaj and traditional Kumari Puja.',
    mustWatch: [
      'One of the oldest community pujas in Kolkata — established 1919',
      'The quintessential classic Sabeki Ekchala Pratima with Daaker Saaj',
      'Illumination display along Bagbazar Street and Circular Canal',
      'Famous Sindoor Khela on Bijoya Dashami morning',
    ],
    artist: 'Subrata Ganguly',
    organizer: 'Bagbazar Sarbojanin Durga Puja Committee',
    established: 1919,
    timings: '24 hours (Saptami to Dashami)',
    bestTime: '9 PM – 11 PM for illumination',
    entryFee: 'Free',
    tags: ['traditional', 'heritage', 'sabeki', 'iconic', 'north-kolkata', 'police-guide'],
    rating: 4.9,
    imageEmoji: '🏛️',
  },
  {
    id: 'kumartuli-park',
    name: 'Kumartuli Park',
    nameBengali: 'কুমারটুলি পার্ক',
    lat: 22.598982700000004,
    lng: 88.36146629999999,
    zone: 'north',
    theme: 'Mrittika Katha',
    themeDescription:
      "Held right in Kumartuli Park ground in the historic clay-modellers colony of Kumartuli, off Rabindra Sarani and Banamali Sarkar Street. Celebrates live idol-crafting.",
    theme2026:  'Mrittika Shilpo & Potter\'s Quarter Heritage',
    themeDescription2026:  'Located in the heart of Kolkata\'s legendary idol-makers colony, celebrating the sacred craft of clay sculpting and traditional Bengal artisans.',
    mustWatch: [
      'Located in Kumartuli Park ground, steps from potters studios',
      'Live idol-making demonstrations by Kumartuli master artisans',
      'Scale clay sculpture installation exceeding 70 feet',
      'Walking distance from Sovabazar Metro Station',
    ],
    artist: 'Mrinmoy Pal',
    organizer: 'Kumartuli Park Sarbojanin',
    established: 1953,
    timings: '8 AM – 3 AM',
    bestTime: '7 PM – 10 PM',
    entryFee: 'Free',
    tags: ['park', 'artisan', 'clay', 'heritage', 'north-kolkata', 'police-guide'],
    rating: 4.9,
    imageEmoji: '🏺',
  },
  {
    id: 'ahiritola',
    name: 'Ahiritola Sarbojanin',
    nameBengali: 'আহিরীটোলা সর্বজনীন',
    lat: 22.5948383,
    lng: 88.3571698,
    zone: 'north',
    theme: 'Gangaar Paare',
    themeDescription:
      "Situated near Ahiritola Ghat and BK Paul Avenue. One of North Kolkata's most celebrated riverfront pujas featuring bold thematic concepts.",
    theme2026:  'Ganga Parer Oitijho (Riverfront Heritage)',
    themeDescription2026:  'Celebrating the sacred Hooghly riverbank heritage with monumental gates, traditional riverine motifs, and vibrant evening aarti.',
    mustWatch: [
      'Minutes from the historic Hooghly River ghats',
      'Intricate traditional idol paired with experimental pandal architecture',
      'Street food paradise along BK Paul Avenue',
    ],
    artist: 'Kaushik Sen',
    organizer: 'Ahiritola Sarbojanin Durgotsab Samity',
    established: 1940,
    timings: '24 hours',
    bestTime: '7 PM – 11 PM',
    entryFee: 'Free',
    tags: ['riverside', 'Ganga', 'heritage', 'police-guide'],
    rating: 4.7,
    imageEmoji: '⛵',
  },
  {
    id: 'hatibagan',
    name: 'Hatibagan Sarbojanin',
    nameBengali: 'হাটিবাগান সর্বজনীন',
    lat: 22.5943863,
    lng: 88.3720004,
    zone: 'north',
    theme: 'Banglar Kutir Shilpa',
    themeDescription:
      "Commanding the legendary Hatibagan crossing at Shri Aurobindo Sarani and Bidhan Sarani. Celebrated for grand heritage pavilions and exquisite lighting.",
    theme2026:  'Purono Kolkatar Smriti (Old Calcutta Nostalgia)',
    themeDescription2026:  'A nostalgic walk through 19th-century North Kolkata lanes, vintage tramways, and classical colonial courtyard architecture.',
    mustWatch: [
      'Iconic North Kolkata location at Hatibagan market junction',
      'Folk art and handloom installations',
      'Surrounded by vintage theatres and Bengali food stalls',
    ],
    artist: 'Debashish Sarkar',
    organizer: 'Hatibagan Sarbojanin Durga Puja',
    established: 1935,
    timings: '8 AM – 3 AM',
    bestTime: '7 PM – 11 PM',
    entryFee: 'Free',
    tags: ['urban', 'heritage', 'north-kolkata', 'police-guide'],
    rating: 4.7,
    imageEmoji: '🎭',
  },
  {
    id: 'nalin-sarkar-street',
    name: 'Nalin Sarkar Street',
    nameBengali: 'নলিন সরকার স্ট্রিট',
    lat: 22.594544199999998,
    lng: 88.3743283,
    zone: 'north',
    theme: 'Kumorer Haath',
    themeDescription:
      "Located just off Shri Aurobindo Sarani near Hatibagan. Famous for experimental environmental designs using natural terracotta and clay.",
    theme2026:  'Shilpi-Mon (The Artist\'s Mind)',
    themeDescription2026:  'Acclaimed for experimental woodwork and intricate handmade artisanal motifs created by Bengal craft masters.',
    mustWatch: [
      'Handcrafted natural materials with zero plastic',
      'Creative interaction with local pottery families',
      'Compact, intense visual artistry',
    ],
    artist: 'The Kumor families of Kumortuli',
    organizer: 'Nalin Sarkar Street Puja Committee',
    established: 1941,
    timings: '8 AM – 2 AM',
    bestTime: '6 PM – 9 PM',
    entryFee: 'Free',
    tags: ['artisan', 'clay', 'terracotta', 'north-kolkata', 'police-guide'],
    rating: 4.7,
    imageEmoji: '🏺',
  },
  {
    id: 'kashi-bose-lane',
    name: 'Kashi Bose Lane',
    nameBengali: 'কাশী বোস লেন',
    lat: 22.590897899999998,
    lng: 88.36891740000002,
    zone: 'north',
    theme: 'Desh O Mati',
    themeDescription:
      "Situated off Vivekananda Road and Bidhan Sarani. Multiple award winner for emotionally gripping thematic installations and social narratives.",
    theme2026:  'Gramin Oitijho O Lok-Shilpo',
    themeDescription2026:  'Celebrated for thought-provoking cultural themes with immersive soundscapes and rich traditional folk artistry of Bengal.',
    mustWatch: [
      'Winner of multiple Asian Paints Sharad Shamman awards',
      'Deeply moving socio-cultural architectural themes',
      'One of the most visited North Kolkata pandals every year',
    ],
    artist: 'Sujoy Prosad Chatterjee',
    organizer: 'Kashi Bose Lane Durga Puja Samiti',
    established: 1937,
    timings: '9 AM – 2 AM',
    bestTime: '7 PM – 11 PM',
    entryFee: 'Free',
    tags: ['award-winning', 'theme', 'heritage', 'north-kolkata', 'police-guide'],
    rating: 4.8,
    imageEmoji: '🏆',
  },
  {
    id: 'maniktala-chaltabagan',
    name: 'Maniktala Chaltabagan Lohapatty',
    nameBengali: 'মানিকতলা চালতাবাগান লোহাপট্টি',
    lat: 22.5835,
    lng: 88.3720,
    zone: 'north',
    theme: 'Utsab & Ekota',
    themeDescription:
      "Set near Maniktala crossing on Raja Rammohan Roy Sarani. Celebrated for dazzling glasswork, brass motifs, and exuberant community Dhunuchi naach.",
    mustWatch: [
      'Spectacular lighting and multi-tiered glasswork chandeliers',
      'Famous Dhunuchi naach competitions attended by celebrities',
      'Centrally located between Vivekananda Road and MG Road',
    ],
    artist: 'Subir Naskar',
    organizer: 'Maniktala Chaltabagan Lohapatty Durgotsav',
    established: 1943,
    timings: '9 AM – 2 AM',
    bestTime: '7 PM – 10 PM',
    entryFee: 'Free',
    tags: ['dhunuchi', 'glasswork', 'illumination', 'police-guide'],
    rating: 4.7,
    imageEmoji: '🪔',
  },
  {
    id: 'tala-pratyay',
    name: 'Tala Pratyay',
    nameBengali: 'তালা প্রত্যয়',
    lat: 22.608791099999998,
    lng: 88.382502,
    zone: 'north',
    theme: 'Riti O Srishti',
    themeDescription:
      "Sprawled across Tala Park ground near Raja Manindra Road and Shyambazar. An architectural powerhouse renowned for monumental museum-quality contemporary art installations.",
    theme2026:  'Shilpo O Shrishti (Art and Genesis)',
    themeDescription2026:  'Pioneering conceptual installation art transforming the entire Tala Park ground into an experiential museum of contemporary Bengal sculpture.',
    mustWatch: [
      'Constructed across the vast grounds of Tala Park',
      'Museum-grade contemporary installations by top Bengal artists',
      'Monumental scale attracting design enthusiasts nationwide',
    ],
    artist: 'Susanta Paul',
    organizer: 'Tala Pratyay Puja Committee',
    established: 1961,
    timings: '24 hours',
    bestTime: '8 PM – 12 AM',
    entryFee: 'Free',
    tags: ['park', 'contemporary-art', 'monumental', 'north-kolkata', 'police-guide'],
    rating: 4.9,
    imageEmoji: '🏛️',
  },
  {
    id: 'telengabagan',
    name: 'Telengabagan',
    nameBengali: 'তেলেঙ্গাবাগান',
    lat: 22.5895,
    lng: 88.3840,
    zone: 'north',
    theme: 'Matir Maa',
    themeDescription:
      "Located along CIT Road near Ultadanga junction. Pioneer of thematic environmental pujas in Kolkata utilizing organic rural crafts.",
    mustWatch: [
      'Pioneer of theme-based pandals in North Kolkata',
      'Eco-friendly rural materials and terracotta installations',
      'Close connectivity from Ultadanga Hudco crossing',
    ],
    artist: 'Tapan Ghosh',
    organizer: 'Telengabagan Sarbojanin Durgotsab',
    established: 1966,
    timings: '6 AM – 2 AM',
    bestTime: '6 PM – 9 PM',
    entryFee: 'Free',
    tags: ['eco', 'terracotta', 'theme', 'police-guide'],
    rating: 4.6,
    imageEmoji: '🌾',
  },
  {
    id: 'belgachia-sadharan',
    name: 'Belgachia Sadharan Durgotsab',
    nameBengali: 'বেলগাছিয়া সাধারণ দুর্গোৎসব',
    lat: 22.6075,
    lng: 88.3850,
    zone: 'north',
    theme: 'Gramin Shilpa & Dokra',
    themeDescription:
      "Highlighted on Zone I (North Kolkata) Police Guide near Belgachia Metro Station. Celebrates rural Bengal cane, dokra, and tribal metalwork.",
    mustWatch: [
      'Over 20,000 bamboo and dokra handcrafted motifs',
      'Direct access from Belgachia Metro Station on Line 1',
      'Kolkata Police priority circulation zone',
    ],
    artist: 'Sanatan Dinda',
    organizer: 'Belgachia Sadharan Puja Committee',
    established: 1949,
    timings: '10 AM – 2 AM',
    bestTime: '7 PM – 11 PM',
    entryFee: 'Free',
    tags: ['dokra', 'metro-access', 'police-guide'],
    rating: 4.6,
    imageEmoji: '🎋',
  },

  // ── Salt Lake & VIP Road (East & North-East) ────────────────────────────────
  {
    id: 'salt-lake-fd',
    name: 'Salt Lake FD Block (FD Park)',
    nameBengali: 'সল্টলেক এফ ডি ব্লক (এফ ডি পার্ক)',
    lat: 22.583454099999997,
    lng: 88.4122701,
    zone: 'east',
    theme: 'Bishwa Bangla & Royal Palace Replica',
    themeDescription:
      "Hosted directly at the expansive FD Park ground in Salt Lake Sector III. Salt Lake's most celebrated mega-pandal, renowned for life-size palace replicas and sprawling mela grounds.",
    theme2026:  'Rajprasader Oitijho (Royal Palace Replica & Festive Carnival)',
    themeDescription2026:  'Salt Lake\'s most celebrated mega-pandal inside FD Park, featuring a grand royal palace replica, vibrant lighting, and an expansive festive mela.',
    mustWatch: [
      'Hosted inside the spacious FD Park ground with wide queue channels',
      'Monumental architectural palace replica with grand lighting',
      'Vibrant open-air mela and food carnival inside the park',
      'Quick pedestrian route from Karunamoyee and Central Park',
    ],
    artist: 'Ayan Mukhopadhyay',
    organizer: 'FD Block Durga Puja Committee',
    established: 1985,
    timings: '10 AM – 1 AM',
    bestTime: '7 PM – 11 PM',
    entryFee: 'Free',
    tags: ['park', 'palace', 'Salt-Lake', 'FD-Park', 'police-guide'],
    rating: 4.8,
    imageEmoji: '🏰',
  },
  {
    id: 'salt-lake-bj',
    name: 'Salt Lake BJ Block (BJ Park)',
    nameBengali: 'সল্টলেক বি জে ব্লক (বি জে পার্ক)',
    lat: 22.5906892,
    lng: 88.4265676,
    zone: 'east',
    theme: 'Gramin Oitijho',
    themeDescription:
      "Held at BJ 415/A beside BJ Park ground near 206 Bus Stand in Salt Lake Sector II. Celebrated for community warmth, artistic pavilions, and family adda.",
    theme2026:  'Gramin Shilpa O Lok-Sanskriti (Rural Folk Crafts)',
    themeDescription2026:  'Located in BJ Park near 206 Bus Stand, showcasing authentic Bengal rural handicrafts, bell metal art, and family adda.',
    mustWatch: [
      'Located directly at BJ Park ground near 206 Bus Stand',
      'Walking distance from Karunamoyee and 206 bus terminus',
      'Traditional handicrafts and tranquil park setting',
    ],
    artist: 'Gopal Dey',
    organizer: 'BJ Block Sarbojanin Durga Puja',
    established: 1984,
    timings: '9 AM – 12 AM',
    bestTime: '6 PM – 10 PM',
    entryFee: 'Free',
    tags: ['park', 'Salt-Lake', 'handicrafts', 'peaceful'],
    rating: 4.6,
    imageEmoji: '🌳',
  },
  {
    id: 'salt-lake-ak',
    name: 'Salt Lake AK Block (AK Park)',
    nameBengali: 'সল্টলেক এ কে ব্লক (এ কে পার্ক)',
    lat: 22.588853699999998,
    lng: 88.4307676,
    zone: 'east',
    theme: 'Alokbortika',
    themeDescription:
      "Situated in AK Park ground, Sector II, Salt Lake. Celebrated for intricate wooden craftsmanship and creative illumination installations.",
    theme2026:  'Kashtha-Kola (Handcrafted Woodwork & Illumination)',
    themeDescription2026:  'Inside AK Park ground, Sector II, celebrated for intricate woodwork, tree-lined avenue illuminations, and community cultural performances.',
    mustWatch: [
      'Inside AK Block park grounds, Sector II',
      'Stunning lighting across the tree-lined avenues of Salt Lake',
      'Traditional Bengali cultural programmes every evening',
    ],
    artist: 'Dipak Ghosh',
    organizer: 'AK Block Association',
    established: 1988,
    timings: '10 AM – 12 AM',
    bestTime: '7 PM – 10 PM',
    entryFee: 'Free',
    tags: ['park', 'Salt-Lake', 'illumination'],
    rating: 4.5,
    imageEmoji: '🪵',
  },
    {
    id: 'salt-lake-cd',
    name: 'Salt Lake CD Block (CD Park)',
    nameBengali: 'সল্টলেক সি ডি ব্লক (সি ডি পার্ক)',
    lat: 22.5919194,
    lng: 88.409485,
    zone: 'east',
    theme: 'Banglar Mati Banglar Jal',
    themeDescription:
      'Held at the CD Park ground in Sector I, Salt Lake, directly adjacent to CD Block 2nd Cross Road and Momo I Am. A beloved community puja known for cultural heritage and green park setting.',
    theme2026:  'Banglar Mati O Sabeki Natmandir',
    themeDescription2026:  'Held in CD Park Sector I right adjacent to Momo I Am, celebrating residential warmth, terracotta idols, and community cultural programs.',
    mustWatch: [
      'Located directly in CD Park, Sector I (right next to Momo I Am test device location)',
      'Beautiful green park ambiance with traditional cultural functions',
      'Artisan idol crafted in terracotta and traditional Bengali motifs',
    ],
    artist: 'Prabir Saha',
    organizer: 'CD Block Residents Association',
    established: 1982,
    timings: '9 AM – 12 AM',
    bestTime: '6 PM – 10 PM',
    entryFee: 'Free',
    tags: ['park', 'Salt-Lake', 'CD-Park', 'neighbourhood', 'near-test-loc'],
    rating: 4.6,
    imageEmoji: '🌿',
  },
{
    id: 'salt-lake-labony',
    name: 'Salt Lake Labony Estate (Labony Park)',
    nameBengali: 'সল্টলেক লাবণী এস্টেট',
    lat: 22.583213100000002,
    lng: 88.40674659999999,
    zone: 'east',
    theme: 'Sabeki Puja & Natmandir',
    themeDescription:
      "Located at Labony Park ground in Sector I, Salt Lake, directly adjacent to 2nd Cross Road and Momo I Am. One of Salt Lake's earliest community pujas.",
    theme2026: '51st Year Sabeki Ekchala Pratima & Natmandir',
    themeDescription2026:
      'Celebrating over five decades of traditional Sabeki Ekchala Pratima with Daaker Saaj in Labony Park ground, right off 2nd Cross Road.',
    mustWatch: [
      'Very close to Momo I Am (Sector 1, CD Block)',
      'Traditional Natmandir structure with Sabeki Pratima',
      'Lively residential adda with authentic home-cooked bhog',
    ],
    artist: 'Labony Resident Artisans',
    organizer: 'Labony Estate Puja Committee',
    established: 1975,
    timings: '8 AM – 12 AM',
    bestTime: '6 PM – 9 PM',
    entryFee: 'Free',
    tags: ['park', 'Salt-Lake', 'traditional', 'near-test-loc'],
    rating: 4.6,
    imageEmoji: '🏛️',
  },
  {
    id: 'sreebhumi',
    name: 'Sreebhumi Sporting Club',
    nameBengali: 'শ্রীভূমি স্পোর্টিং ক্লাব',
    lat: 22.5988987,
    lng: 88.4029328,
    zone: 'north',
    theme: 'Angkor Wat & Royal Architecture',
    themeDescription:
      "Commanding Canal Street off VIP Road in Lake Town. Unquestionably Kolkata's most viral pandal, famed for monumental world wonder replicas with gold-plated ornaments.",
    theme2026:  'Hawa Mahal of Jaipur',
    themeDescription2026:  'A magnificent architectural recreation of Jaipur\'s iconic Hawa Mahal (Palace of Winds), featuring intricate pink sandstone facades, ornate jharokha windows, and royal Rajasthani illumination.',
    mustWatch: [
      'Most-photographed pandal in Eastern India',
      'Durga Pratima adorned with real gold and diamond jewellery',
      'Spectacular VIP Road illumination corridor spanning 2 km',
      'High security and Kolkata Police special traffic regulation',
    ],
    artist: 'Sushanta Pal',
    organizer: 'Sreebhumi Sporting Club',
    established: 1969,
    timings: '24 hours',
    bestTime: '7 PM – 11 PM (sound & light show)',
    entryFee: 'Free',
    tags: ['grand', 'replica', 'photo-worthy', 'VIP-road', 'iconic', 'police-guide'],
    rating: 4.8,
    imageEmoji: '🏯',
  },
  {
    id: 'dum-dum-park',
    name: 'Dum Dum Park Bharat Chakra',
    nameBengali: 'দম দম পার্ক ভারত চক্র',
    lat: 22.610821299999998,
    lng: 88.4146001,
    zone: 'east',
    theme: 'Bharat 2047 & Shilpa Sanskriti',
    themeDescription:
      "Located inside Dum Dum Park neighborhood. Consistently ranks among Kolkata's top ten theme pujas for boundary-pushing artistic architecture.",
    theme2026:  'Samajik Chetana (Social Consciousness)',
    themeDescription2026:  'Innovative socio-cultural art installation blending contemporary environmental awareness with Bengal\'s rich aesthetic tradition.',
    mustWatch: [
      'Exceptional architectural craftsmanship by master Bengal sculptors',
      'Part of the famous Dum Dum Park trio circuit',
      'Easy access from VIP Road and Jessore Road',
    ],
    artist: 'Subhajit Das',
    organizer: 'Dum Dum Park Bharat Chakra',
    established: 1956,
    timings: '10 AM – 2 AM',
    bestTime: '7 PM – 11 PM',
    entryFee: 'Free',
    tags: ['contemporary-art', 'award-winning', 'theme', 'police-guide'],
    rating: 4.8,
    imageEmoji: '🇮🇳',
  },
  {
    id: 'dum-dum-tarun-sangha',
    name: 'Dum Dum Park Tarun Sangha',
    nameBengali: 'দম দম পার্ক তরুণ সংঘ',
    lat: 22.6094363,
    lng: 88.4164052,
    zone: 'east',
    theme: 'Anando Dhara',
    themeDescription:
      "Situated around Dum Dum Park Tank 3. Renowned for reflective water installations, organic materials, and multiple Sharad Shamman trophies.",
    theme2026:  'Matir Shur (Melody of the Earth)',
    themeDescription2026:  'Artisanal terracotta and pottery motifs celebrating Bengal\'s soil, rural folk songs, and ecological connection.',
    mustWatch: [
      'Lakeside reflection creates stunning visual symmetry at night',
      'Multiple Asian Paints Sharad Shamman winning committee',
      'Step-free accessible queue corridor',
    ],
    artist: 'Rintu Das',
    organizer: 'Dum Dum Park Tarun Sangha',
    established: 1972,
    timings: '10 AM – 2 AM',
    bestTime: '7 PM – 10 PM',
    entryFee: 'Free',
    tags: ['water-reflection', 'award-winning', 'theme', 'police-guide'],
    rating: 4.7,
    imageEmoji: '🌊',
  },

  // ── South Kolkata & Southern Avenue / Gariahat Parks ────────────────────────
  {
    id: 'maddox-square',
    name: 'Maddox Square',
    nameBengali: 'ম্যাডক্স স্কোয়ার',
    lat: 22.5265634,
    lng: 88.3546477,
    zone: 'south',
    theme: 'Sabeki Ekchala & Iconic Park Adda',
    themeDescription:
      "Kolkata's most beloved park puja, sprawling across the lush lawns of Maddox Square Park in Hazra/Ballygunge. Famous for traditional Ekchala Pratima, open-air park adda, and aristocratic ambiance.",
    theme2026:  'Sabeki Heritage & Park Adda',
    themeDescription2026:  'South Kolkata\'s iconic open-park gathering, featuring traditional Ekchala Durga Pratima under an expansive white shamiana, centered around joyous family adda.',
    mustWatch: [
      'The quintessential Kolkata Durga Puja open-air park adda on green lawns',
      'Traditional Sabeki Ekchala Pratima with Daaker Saaj',
      'Lush park lawn setting where thousands gather every evening',
      'Walking distance from Hazra Road, Lansdowne, and Ballygunge',
    ],
    artist: 'Traditional Committee Artisans',
    organizer: 'Maddox Square Puja Committee',
    established: 1935,
    timings: '24 hours',
    bestTime: '5 PM – 11 PM',
    entryFee: 'Free',
    tags: ['park', 'adda', 'sabeki', 'traditional', 'south-kolkata', 'police-guide'],
    rating: 4.9,
    imageEmoji: '🌳',
  },
  {
    id: 'deshapriya-park',
    name: 'Deshapriya Park',
    nameBengali: 'দেশপ্রিয় পার্ক',
    lat: 22.518581899999997,
    lng: 88.3534607,
    zone: 'south',
    theme: 'Rajbari & Monumental Architecture',
    themeDescription:
      "Held right inside the spacious grounds of Deshapriya Park on Rashbehari Avenue, adjacent to Priya Cinema. One of the highest-footfall pujas in South Kolkata.",
    theme2026:  'Monumental Mandir & Kolkata Oitijho',
    themeDescription2026:  'A grand architectural temple spectacle on Rashbehari Avenue, celebrated for monumental scale, traditional grandeur, and vibrant cultural festivities.',
    mustWatch: [
      'Sprawls across the massive Deshapriya Park cricket grounds',
      'Monumental architectural structure visible from Rashbehari Avenue',
      'Epicentre of the Gariahat–Rashbehari puja hopping corridor',
      'Kolkata Police priority transit channel',
    ],
    artist: 'Partha Dasgupta',
    organizer: 'Deshapriya Park Durgotsav',
    established: 1938,
    timings: '10 AM – 3 AM',
    bestTime: '8 PM – 12 AM',
    entryFee: 'Free',
    tags: ['park', 'grand', 'Rashbehari', 'south-kolkata', 'police-guide'],
    rating: 4.8,
    imageEmoji: '🏛️',
  },
  {
    id: 'tridhara',
    name: 'Tridhara Sammilani',
    nameBengali: 'ত্রিধারা সম্মিলনী',
    lat: 22.519528599999997,
    lng: 88.3554398,
    zone: 'south',
    theme: 'Utsaber Ronge',
    themeDescription:
      "Located at the bustling tri-junction of Monoharpukur Road, Mahanirban Road, and Rashbehari Avenue. World-renowned for cutting-edge conceptual themes.",
    theme2026:  'Prokriti O Prana (Nature & Life Force)',
    themeDescription2026:  'Contemporary artistic exploration of natural elements, forest life, and spiritual vitality crafted with sustainable organic media.',
    mustWatch: [
      'Featured prominently in Zone II of the Kolkata Police Guide',
      'Spectacular lighting along Monoharpukur and Rashbehari Avenue',
      'Masterpiece installations by Bengal’s foremost visual artists',
    ],
    artist: 'Gouranga Kuila',
    organizer: 'Tridhara Sammilani',
    established: 1947,
    timings: '24 hours',
    bestTime: '7 PM – 11 PM',
    entryFee: 'Free',
    tags: ['award-winning', 'theme', 'Rashbehari', 'police-guide'],
    rating: 4.8,
    imageEmoji: '🎭',
  },
  {
    id: 'singhi-park',
    name: 'Singhi Park',
    nameBengali: 'সিংঘী পার্ক',
    lat: 22.5209489,
    lng: 88.3627281,
    zone: 'south',
    theme: 'Bharat Tirtha Temple Architecture',
    themeDescription:
      "Situated along Dover Lane and Dover Terrace in Gariahat. Famous for recreating magnificent stone temple replicas of India with authentic architectural details.",
    theme2026:  'Indian Temple Architecture & Classical Illumination',
    themeDescription2026:  'Recreating majestic Indian stone temple facades at Dover Lane with world-famous Chandannagar electrical lighting artistry.',
    mustWatch: [
      'Recreation of historic Indian temple architecture',
      'Pristine Chandannagar lighting displays along Dover Lane',
      'Located steps away from Ekdalia Evergreen in the Gariahat hub',
    ],
    artist: 'Babu Pal',
    organizer: 'Singhi Park Sarbojanin Durga Puja',
    established: 1941,
    timings: '10 AM – 2 AM',
    bestTime: '7 PM – 11 PM',
    entryFee: 'Free',
    tags: ['temple-replica', 'heritage', 'Gariahat', 'police-guide'],
    rating: 4.7,
    imageEmoji: '🛕',
  },
  {
    id: 'hindustan-park',
    name: 'Hindustan Park',
    nameBengali: 'হিন্দুস্তান পার্ক',
    lat: 22.5176792,
    lng: 88.3620716,
    zone: 'south',
    theme: 'Banglar Mati O Mon',
    themeDescription:
      "Set inside Hindustan Park off Gariahat Road. A connoisseur favourite that marries sensitive folk art traditions with modern spatial installations.",
    theme2026:  'Lok-Shilpo O Shrishti (Folk Art & Genesis)',
    themeDescription2026:  'Intimate South Kolkata artistic pavilion featuring handcrafted dokra, patachitra, and soulful community celebrations.',
    mustWatch: [
      'Charming residential park atmosphere off Gariahat',
      'Intricate use of organic and handcrafted materials',
      'Surrounded by South Kolkata’s iconic boutiques and cafes',
    ],
    artist: 'Anirban Majumder',
    organizer: 'Hindustan Park Sarbojanin Durgotsav',
    established: 1930,
    timings: '9 AM – 2 AM',
    bestTime: '6 PM – 10 PM',
    entryFee: 'Free',
    tags: ['park', 'folk-art', 'Gariahat', 'police-guide'],
    rating: 4.7,
    imageEmoji: '🎨',
  },
  {
    id: 'ekdalia-evergreen',
    name: 'Ekdalia Evergreen',
    nameBengali: 'একডালিয়া এভারগ্রিন',
    lat: 22.5212187,
    lng: 88.3665629,
    zone: 'south',
    theme: 'Sabeki Pratima & German Chandelier',
    themeDescription:
      "At Ekdalia Road and Suren Tagore Road in Gariahat. Kolkata’s most prestigious traditional puja, renowned for towering chandeliers imported from Europe and classic idol artistry.",
    theme2026:  'South Indian Temple Splendour & German Chandelier',
    themeDescription2026:  'Grand classical South Indian temple structure featuring authentic architectural carvings, their signature European chandelier, and revered traditional idol.',
    mustWatch: [
      'Mammoth European crystal chandelier suspended above the Goddess',
      'Pure traditional Sabeki pratima with exquisite golden ornaments',
      'Unmatched illumination spanning the entire Gariahat flyover corridor',
      'A South Kolkata pilgrimage spot for over 80 years',
    ],
    artist: 'Traditional Artisans & European Lighting Masters',
    organizer: 'Ekdalia Evergreen Club',
    established: 1943,
    timings: '24 hours',
    bestTime: '8 PM – 1 AM',
    entryFee: 'Free',
    tags: ['sabeki', 'chandelier', 'traditional', 'Gariahat', 'police-guide'],
    rating: 4.8,
    imageEmoji: '💎',
  },
  {
    id: 'ballygunge-cultural',
    name: 'Ballygunge Cultural Association',
    nameBengali: 'বালিগঞ্জ কালচারাল',
    lat: 22.516212200000002,
    lng: 88.3558059,
    zone: 'south',
    theme: 'Tradition Meets Tomorrow',
    themeDescription:
      "Featured prominently in Zone II of the Police Guide on Lake Temple Road and Fern Road. Celebrated for aristocratic pedigree, serene aesthetics, and pristine Pratima.",
    theme2026:  'Banglar Lok-Parampara (Bengal Folk Traditions)',
    themeDescription2026:  '75-year-old cultural institution celebrating the rich heritage of Bengal folk arts, community bhog, and classical idol craftsmanship.',
    mustWatch: [
      'Sabeki Ekchala idol with real gold and silver foil ornamentation',
      'Art exhibitions hosted inside the community hall',
      'Traditional Dhak rhythms by Murshidabad dhakis',
    ],
    artist: 'Pradip Das',
    organizer: 'Ballygunge Cultural Association',
    established: 1951,
    timings: '10 AM – 2 AM',
    bestTime: '6 PM – 10 PM',
    entryFee: 'Free',
    tags: ['aristocratic', 'traditional', 'Ballygunge', 'police-guide'],
    rating: 4.8,
    imageEmoji: '🎭',
  },
  {
    id: 'mudiali-club',
    name: 'Mudiali Club',
    nameBengali: 'মুদিয়ালী ক্লাব',
    lat: 22.510194,
    lng: 88.3463122,
    zone: 'south',
    theme: 'Praner Spandan & Eco-Lighting',
    themeDescription:
      "Classic Southern Avenue grandeur featured prominently on Kolkata Police Zone II guide. Celebrated for eco-conscious lighting, glass decor, and synchronized chandeliers.",
    theme2026:  'Nirman O Shrishti (Creation & Nature)',
    themeDescription2026:  'Acclaimed for environmental harmony, pure vegetarian idol aesthetics, and nature-inspired architectural artistry.',
    mustWatch: [
      'Signature chandelier illumination over 40 feet high',
      'Over 85 years of uninterrupted puja tradition',
      'Direct walking route to Shib Mandir and Rabindra Sarobar Lake',
    ],
    artist: 'Gouranga Kuila',
    organizer: 'Mudiali Club Puja Committee',
    established: 1935,
    timings: '9 AM – 3 AM',
    bestTime: '7 PM – 11 PM',
    entryFee: 'Free',
    tags: ['classic', 'lighting', 'Southern-Avenue', 'police-guide'],
    rating: 4.8,
    imageEmoji: '✨',
  },
  {
    id: 'shib-mandir',
    name: 'Shib Mandir Sarbojanin',
    nameBengali: 'শিব মন্দির সর্বজনীন',
    lat: 22.5109975,
    lng: 88.3498496,
    zone: 'south',
    theme: 'Matribhumi',
    themeDescription:
      "Located on Lake View Road off Southern Avenue. Renowned for experimental clay architecture, ecological consciousness, and proximity to Rabindra Sarobar.",
    theme2026:  'Adhyatmik Chetana (Spiritual Consciousness)',
    themeDescription2026:  'Located on Lake Temple Road near Menoka Cinema, known for deeply spiritual thematic concepts and artistic serenity.',
    mustWatch: [
      'Intricate clay installations by master potters',
      'Lakeside breeze and proximity to Rabindra Sarobar Lake',
      'Eco-friendly natural paints and zero-plastic installation',
    ],
    artist: 'Bhabatosh Sutar',
    organizer: 'Shib Mandir Puja Committee',
    established: 1936,
    timings: '9 AM – 2 AM',
    bestTime: '8 PM – 12 AM',
    entryFee: 'Free',
    tags: ['clay', 'sculpture', 'lake', 'police-guide'],
    rating: 4.7,
    imageEmoji: '🏛️',
  },
  {
    id: 'badamtala-ashar-sangha',
    name: 'Badamtala Ashar Sangha',
    nameBengali: 'বাদামতলা আশার সংঘ',
    lat: 22.517966800000004,
    lng: 88.3437245,
    zone: 'south',
    theme: 'Aalo O Chhaaya',
    themeDescription:
      "Commanding Nepal Bhattacharjee Street near Kalighat Metro and Rashbehari Crossing. International award winner for contemporary architectural brilliance.",
    theme2026:  'Samajik Shilpo (Social Canvas)',
    themeDescription2026:  'Renowned pioneer of theme pujas in South Kolkata, creating thought-provoking contemporary visual installations.',
    mustWatch: [
      'Pioneer of South Kolkata avant-garde theme installations',
      'Direct access from Kalighat Metro Station (Line 1)',
      'Partnered circuit with 66 Pally and Nepal Bhattacharjee Street',
    ],
    artist: 'Snehasish Maity',
    organizer: 'Badamtala Ashar Sangha',
    established: 1939,
    timings: '8 AM – 2 AM',
    bestTime: '7 PM – 11 PM',
    entryFee: 'Free',
    tags: ['contemporary-art', 'metro-access', 'police-guide'],
    rating: 4.8,
    imageEmoji: '🕯️',
  },
  {
    id: '66-pally',
    name: '66 Pally',
    nameBengali: '৬৬ পল্লী',
    lat: 22.5180613,
    lng: 88.34275260000001,
    zone: 'south',
    theme: 'Nari Shakti & Sanskriti',
    themeDescription:
      "On Nepal Bhattacharjee Street in Kalighat. Made history with female priest consecrations and cutting-edge social design.",
    theme2026:  'Oitijho O Somokal (Tradition & Modernity)',
    themeDescription2026:  'Famous for historic social milestones (such as female priests) and inclusive, progressive community celebration.',
    mustWatch: [
      'Historically famous for female priest-led puja rituals',
      'Walking distance from Kalighat Kali Temple and Kalighat Metro',
      'Intricate wooden and textile installations',
    ],
    artist: 'Pritha Mukherjee',
    organizer: '66 Pally Sarbojanin',
    established: 1947,
    timings: '10 AM – 2 AM',
    bestTime: '7 PM – 11 PM',
    entryFee: 'Free',
    tags: ['heritage', 'social', 'Kalighat', 'police-guide'],
    rating: 4.7,
    imageEmoji: '🕊️',
  },
  {
    id: 'chetla-agrani',
    name: 'Chetla Agrani',
    nameBengali: 'চেতলা অগ্রণী',
    lat: 22.516399699999997,
    lng: 88.3368366,
    zone: 'south',
    theme: 'Rang Beranger Mati',
    themeDescription:
      "Located at Chetla Central Road. A perennial frontrunner in the Kolkata Puja Carnival for monumental architecture and organic dye installations.",
    theme2026:  'Antorjyoti (The Awakening Inner Light)',
    themeDescription2026:  'An inspiring visual and spiritual installation exploring the inner light of consciousness through artisanal rural craftsmanship and clay art.',
    mustWatch: [
      'Won Best Illumination at Kolkata Puja Carnival',
      'Natural dye workshop for visitors every afternoon',
      'Idol draped in hand-block-printed fabric by Shantiniketan weavers',
    ],
    artist: 'Subrata Banerjee',
    organizer: 'Chetla Agrani Club',
    established: 1955,
    timings: '10 AM – 2 AM',
    bestTime: '8 PM – 11 PM',
    entryFee: 'Free',
    tags: ['carnival-winner', 'natural-dye', 'craft', 'police-guide'],
    rating: 4.8,
    imageEmoji: '🎨',
  },
  {
    id: 'suruchi-sangha',
    name: 'Suruchi Sangha',
    nameBengali: 'সুরুচি সংঘ',
    lat: 22.508985499999998,
    lng: 88.3339522,
    zone: 'south',
    theme: 'Patachitra Parab & State Culture',
    themeDescription:
      "Located on Station Road in New Alipore. Renowned for celebrating different Indian state cultures and Bengal folk art with massive thematic pavilions.",
    theme2026:  'Padma (The Eternal Lotus)',
    themeDescription2026:  'Highlighting the sacred lotus flower as an eternal symbol of Indian spiritual heritage, purity, and artistic resilience with organic materials and handwoven crafts.',
    mustWatch: [
      'Sprawling New Alipore complex with thematic state architecture',
      'Original theme music composed by leading Bengali music directors',
      'Vibrant cultural performances and artisanal display booths',
    ],
    artist: 'Subrata Banerjee',
    organizer: 'Suruchi Sangha Club',
    established: 1954,
    timings: '8 AM – 2 AM',
    bestTime: '6 PM – 10 PM',
    entryFee: 'Free',
    tags: ['folk-art', 'patachitra', 'New-Alipore', 'police-guide'],
    rating: 4.7,
    imageEmoji: '🎨',
  },
  {
    id: 'bosepukur',
    name: 'Bosepukur Sitala Mandir',
    nameBengali: 'বোসপুকুর সীতলা মন্দির',
    lat: 22.5192181,
    lng: 88.38485759999999,
    zone: 'south',
    theme: 'Bishnupur Brindabon',
    themeDescription:
      "Located on Bosepukur Road in Kasba. World-famous since 2001 for pioneering unconventional eco-friendly materials and terracotta preservation.",
    theme2026:  'Banglar Matir Shilpo (Bengal Clay Art)',
    themeDescription2026:  'Pioneers of raw material themes, creating innovative artistic installations celebrating traditional clay craftsmanship.',
    mustWatch: [
      'Built with authentic terracotta sourced from Bishnupur artisans',
      'UNESCO heritage recognition for terracotta art preservation',
      'Bishnupuri classical dance performances every evening',
    ],
    artist: 'Kartick Dey',
    organizer: 'Bosepukur Sitala Mandir Puja Committee',
    established: 1950,
    timings: '8 AM – 2 AM',
    bestTime: '7 PM – 10 PM',
    entryFee: 'Free',
    tags: ['terracotta', 'heritage', 'Kasba', 'police-guide'],
    rating: 4.7,
    imageEmoji: '🧱',
  },
  {
    id: 'rajdanga-naba-uday',
    name: 'Rajdanga Naba Uday Sangha',
    nameBengali: 'রাজডাঙা নবোদয় সংঘ',
    lat: 22.5130,
    lng: 88.3960,
    zone: 'east',
    theme: 'Shilpa Sanskriti',
    themeDescription:
      "Situated in Kasba Rajdanga near Ruby and Kasba New Market. Known for massive sculptural scale and experimental rural craft installations.",
    mustWatch: [
      'Monumental sculpture visible from the Kasba connector',
      'Craft installations featuring rural artisans working live',
      'Well-organized queue management near EM Bypass',
    ],
    artist: 'Rohit Bose',
    organizer: 'Rajdanga Naba Uday Sangha',
    established: 1963,
    timings: '10 AM – 1 AM',
    bestTime: '6 PM – 10 PM',
    entryFee: 'Free',
    tags: ['craft', 'monumental', 'Kasba', 'police-guide'],
    rating: 4.6,
    imageEmoji: '💻',
  },
  {
    id: 'jodhpur-park',
    name: 'Jodhpur Park',
    nameBengali: 'যোধপুর পার্ক',
    lat: 22.508235,
    lng: 88.3627602,
    zone: 'south',
    theme: 'Aranya Katha',
    themeDescription:
      "Held in Jodhpur Park Boys School ground and Jodhpur Park. Famous for lush botanical themes, environmental conservation, and serene neighborhood ambience.",
    theme2026:  'Prakriti O Samaj (Nature and Society)',
    themeDescription2026:  'Expansive South Kolkata puja in Jodhpur Park ground, combining grand scale with eco-friendly concepts.',
    mustWatch: [
      'Set inside spacious Jodhpur Park school ground',
      'Thousands of living plants integrated into pandal architecture',
      'Walking distance from South City Mall and Prince Anwar Shah Road',
    ],
    artist: 'Somenath Pal',
    organizer: 'Jodhpur Park Sarbojanin Durgotsab',
    established: 1952,
    timings: '9 AM – 1 AM',
    bestTime: '8 PM – 11 PM',
    entryFee: 'Free',
    tags: ['park', 'nature', 'eco', 'Jodhpur-Park', 'police-guide'],
    rating: 4.7,
    imageEmoji: '🌿',
  },
  {
    id: 'babubagan',
    name: 'Babubagan Sarbojanin',
    nameBengali: 'বাবুবাগান সর্বজনীন',
    lat: 22.5079875,
    lng: 88.3685745,
    zone: 'south',
    theme: 'Mandir Sthapatya',
    themeDescription:
      "Situated in Dhakuria near Babubagan bus stand. Famous for recreating heritage stone temples using commemorative coins, terracotta, and copper.",
    theme2026:  'Pratno-Shilpo (Archaeological Heritage of India)',
    themeDescription2026:  'Held at Babubagan Playground, Dhakuria, celebrated for breathtaking replicas of UNESCO World Heritage temples and monuments.',
    mustWatch: [
      'Intricate coin and metal relief work',
      'Close to Dhakuria Railway Station and Selimpur Road',
      'Classic heritage lighting and idol craftsmanship',
    ],
    artist: 'Sujit Ghosh',
    organizer: 'Babubagan Sarbojanin Durgotsav',
    established: 1962,
    timings: '9 AM – 1 AM',
    bestTime: '7 PM – 10 PM',
    entryFee: 'Free',
    tags: ['temple-art', 'Dhakuria', 'police-guide'],
    rating: 4.6,
    imageEmoji: '🏛️',
  },
  {
    id: 'selimpur-pally',
    name: 'Selimpur Pally',
    nameBengali: 'সেলিমপুর পল্লী',
    lat: 22.504677599999997,
    lng: 88.36836629999999,
    zone: 'south',
    theme: 'Banglar Sahitya O Shilpa',
    themeDescription:
      "Located on Selimpur Road in Dhakuria. Known for literary and poetic thematic installations paired with classical idol craftsmanship.",
    theme2026:  'Lok-Chitro (Bengal Pattachitra & Folk Painting)',
    themeDescription2026:  'Immersive artistic pavilion highlighting traditional Bengal rural folk paintings and artisanal storytelling.',
    mustWatch: [
      'Literary manuscripts and Bengali typography installations',
      'Part of the Dhakuria–Jodhpur Park south cluster',
      'Atmospheric evening musical soirees',
    ],
    artist: 'Mrityunjoy Basu',
    organizer: 'Selimpur Pally Durgotsav',
    established: 1955,
    timings: '9 AM – 1 AM',
    bestTime: '7 PM – 10 PM',
    entryFee: 'Free',
    tags: ['literature', 'Dhakuria', 'police-guide'],
    rating: 4.6,
    imageEmoji: '✍️',
  },

  // ── South Suburban, Behala & Port ──────────────────────────────────────────
  {
    id: 'naktala-udayan',
    name: 'Naktala Udayan Sangha',
    nameBengali: 'নাকতলা উদয়ন সংঘ',
    lat: 22.4742929,
    lng: 88.3665898,
    zone: 'south',
    theme: 'Narir Shakti & Contemporary Grandeur',
    themeDescription:
      "Located on NSC Bose Road near Gitanjali (Naktala) Metro Station. A juggernaut of South Kolkata known for radical, award-winning contemporary installations.",
    theme2026:  'Shilpo-Bhabna (Conceptual Sculpture)',
    themeDescription2026:  'One of Kolkata\'s premier mega-budget theme installations, renowned for avant-garde sculpture and monumental creative architecture.',
    mustWatch: [
      'Pacesetter for Bengal contemporary design installations',
      'Short walk from Gitanjali Metro Station (Line 1)',
      'Multiple Asian Paints Sharad Shamman winning committee',
    ],
    artist: 'Bhabatosh Sutar',
    organizer: 'Naktala Udayan Sangha',
    established: 1950,
    timings: '10 AM – 2 AM',
    bestTime: '8 PM – 11 PM',
    entryFee: 'Free',
    tags: ['metro-access', 'award-winning', 'contemporary-art', 'police-guide'],
    rating: 4.9,
    imageEmoji: '💪',
  },
  {
    id: 'behala-nutan-dal',
    name: 'Behala Nutan Dal',
    nameBengali: 'বেহালা নূতন দল',
    lat: 22.5002078,
    lng: 88.320287,
    zone: 'south',
    theme: 'Sitar-er Sur & Musical Architecture',
    themeDescription:
      "Situated near Behala Tram Depot on Diamond Harbour Road. Famous for architectural installations inspired by Indian classical musical instruments.",
    theme2026:  'Banglar Sanskriti (Bengal\'s Living Culture)',
    themeDescription2026:  'Behala\'s top-tier theme pandal, known for grand artisanal craftsmanship and vibrant evening cultural festivals.',
    mustWatch: [
      'Sprawling musical instrument pavilion design',
      'Direct connectivity via Diamond Harbour Road',
      'Key stop on the Behala puja hopping trail',
    ],
    artist: 'Palash Das',
    organizer: 'Behala Nutan Dal',
    established: 1957,
    timings: '10 AM – 1 AM',
    bestTime: '8 PM – 11 PM',
    entryFee: 'Free',
    tags: ['music', 'classical', 'Behala', 'police-guide'],
    rating: 4.7,
    imageEmoji: '🎸',
  },
  {
    id: 'barisha-club',
    name: 'Barisha Club',
    nameBengali: 'বারিশা ক্লাব',
    lat: 22.4812859,
    lng: 88.3132412,
    zone: 'south',
    theme: 'Bhorer Aalo',
    themeDescription:
      "Located at Sakher Bazar on Diamond Harbour Road in Behala. Acclaimed globally for empathetic sculptures highlighting human migration and environmental resilience.",
    theme2026:  'Manobotar Jayagaan (Tribute to Humanity)',
    themeDescription2026:  'Celebrated across the world for deeply moving, socially resonant themes that touch the hearts of millions of visitors.',
    mustWatch: [
      'World-famous socio-cultural sculpture installations',
      'Heart of Behala Sakher Bazar puja festivities',
      'Police designated pedestrian lane along Diamond Harbour Road',
    ],
    artist: 'Rintu Das',
    organizer: 'Barisha Club',
    established: 1948,
    timings: '8 AM – 1 AM',
    bestTime: '7 PM – 10 PM',
    entryFee: 'Free',
    tags: ['sculpture', 'social', 'Behala', 'police-guide'],
    rating: 4.8,
    imageEmoji: '🐯',
  },
  {
    id: 'haridevpur-ajeyo-sanghati',
    name: 'Haridevpur Ajeyo Sanghati',
    nameBengali: 'অজেয় সংহতি',
    lat: 22.4808597,
    lng: 88.33770530000001,
    zone: 'south',
    theme: 'Matir Gandho',
    themeDescription:
      "Featured prominently in Zone IV (Jadavpur & Behala Division) on the Kolkata Police guide. World-class conceptual art pandal spanning open grounds.",
    theme2026:  'Lok-Dharani (Earth & Folk Traditions)',
    themeDescription2026:  'Renowned South Kolkata crowd-puller featuring grand environmental themes and traditional idol artistry.',
    mustWatch: [
      'Multiple Asian Paints Sharad Shamman winning committee',
      'Monumental architectural installation spanning open playground',
      'Dedicated one-way traffic route mapped by Kolkata Police',
    ],
    artist: 'Aditi Chakraborty',
    organizer: 'Ajeyo Sanghati Club',
    established: 1968,
    timings: '10 AM – 3 AM',
    bestTime: '8 PM – 1 AM',
    entryFee: 'Free',
    tags: ['award-winning', 'suburban', 'police-guide'],
    rating: 4.8,
    imageEmoji: '🏆',
  },
  {
    id: 'park-circus',
    name: 'Park Circus Sarbojanin',
    nameBengali: 'পার্ক সার্কাস সর্বজনীন',
    lat: 22.543478999999998,
    lng: 88.36765439999999,
    zone: 'central',
    theme: 'Ek Kolkata, Anek Rangee',
    themeDescription:
      "Sprawled across the Park Circus Maidan ground. Celebrates Kolkata's multicultural harmony with massive food stalls, biryani stalls, and vibrant festive lighting.",
    theme2026:  'Sompriiti (Harmony & Unity)',
    themeDescription2026:  'Expansive community celebration on Park Circus Maidan symbolizing communal harmony and cultural unity.',
    mustWatch: [
      'Set inside the vast Park Circus Maidan ground',
      'Kolkata’s famous multicultural unity on display',
      'Epicentre of Kolkata festive street food and biryani',
    ],
    artist: 'Sudipta Mondal',
    organizer: 'Park Circus Sarbojanin',
    established: 1944,
    timings: '10 AM – 1 AM',
    bestTime: '7 PM – 10 PM',
    entryFee: 'Free',
    tags: ['maidan', 'park', 'food', 'harmony', 'police-guide'],
    rating: 4.6,
    imageEmoji: '🤝',
  },
  {
    id: 'kabitirtha-75-palli',
    name: 'Kabitirtha 75 Palli (Kidderpore)',
    nameBengali: 'কবিতীর্থ ৭৫ পল্লী',
    lat: 22.5406238,
    lng: 88.3223506,
    zone: 'south',
    theme: 'Kabir Desh',
    themeDescription:
      "Major highlight of Zone III (Port Area) on the Kolkata Police map. Located on Dent Mission Road in Kidderpore, dedicated to Bengal's literary icons.",
    theme2026:  'Kabita O Shilpo (Poetry & Art)',
    themeDescription2026:  'Kidderpore\'s premier celebration paying homage to Michael Madhusudan Dutt and Bengal\'s literary renaissance.',
    mustWatch: [
      'Featured prominently in Zone III (Port Area) of Police Guide',
      'Literary manuscripts reproduced in terracotta relief',
      'Police assistance booth located right outside pandal gate',
    ],
    artist: 'Debatosh Kar',
    organizer: '75 Palli Sarbojanin',
    established: 1965,
    timings: '10 AM – 2 AM',
    bestTime: '7 PM – 10 PM',
    entryFee: 'Free',
    tags: ['port', 'poetry', 'Kidderpore', 'police-guide'],
    rating: 4.6,
    imageEmoji: '📜',
  },
  {
    id: 'khidderpore-28',
    name: 'Khidderpore 28 Palli',
    nameBengali: 'খিদিরপুর ২৮ পল্লী',
    lat: 22.5391961,
    lng: 88.32645649999999,
    zone: 'south',
    theme: 'Bondar Kotha',
    themeDescription:
      "On Karl Marx Sarani in the historic port area. Celebrates 200 years of Kolkata Port connecting Bengal to the oceans.",
    theme2026:  'Sampriti Oitijho (Heritage of the Port City)',
    themeDescription2026:  'Vibrant community celebration celebrating the cosmopolitan cultural tapestry of the Kolkata port district.',
    mustWatch: [
      'Built from reclaimed maritime materials and authentic dock rope',
      'Life-size cargo dock recreation from the 1920s',
      'Night illumination reflected in the water channels',
    ],
    artist: 'Prosenjit Mondal',
    organizer: 'Khidderpore 28 Palli',
    established: 1946,
    timings: '10 AM – 2 AM',
    bestTime: '8 PM – 11 PM',
    entryFee: 'Free',
    tags: ['port', 'maritime', 'history', 'police-guide'],
    rating: 4.6,
    imageEmoji: '⚓',
  },
];

/** Returns crowd descriptor based on simulated intensity */
export function crowdLevel(count: number): {
  label: string;
  color: string;
  emoji: string;
} {
  if (count < 30) return { label: 'Light', color: '#22C55E', emoji: '🟢' };
  if (count < 80) return { label: 'Moderate', color: '#F59E0B', emoji: '🟡' };
  if (count < 150) return { label: 'Crowded', color: '#F97316', emoji: '🟠' };
  return { label: 'Very Crowded', color: '#EF4444', emoji: '🔴' };
}

/** Get simulated point-level crowd count near a pandal based on time */
export function getSimulatedCrowdForPandal(pandalId: string): number {
  const hour = new Date().getHours();
  const isEvening = hour >= 18 || hour <= 2;
  const isPeak = (hour >= 20 && hour <= 23) || hour <= 1;
  const base = isPeak ? 180 : isEvening ? 100 : 35;
  // Deterministic but pseudo-random per pandal
  const seed = pandalId.split('').reduce((a, c) => a + c.charCodeAt(0), 0);
  return Math.floor(base * (0.6 + (seed % 10) / 25));
}
